sudo: required
services:
    - docker
language: java

before_install:
    - docker build -t naikamit/dwz-ex -f Dockerfile .

script:
    - mvn test 

after_success:
    - echo "$DOCKER_PD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push naikamit2016/dwz-ex