sudo: required
services:
    - docker
language: java

script:
    - docker build -t dwz-ex -f Dockerfile .

after_success:
    - echo "$DOCKER_PD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dwz-ex