version: '3'
services:
   dwz-ex:
      build: 
         dockerfile: Dockerfile
         context: .
      expose:
        - 8080
        - 8081
      ports:
        - "8080:8080"
        - "8081:8081"